TaskPlatform/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url, include

from web.views import home, account, project, dashboard, wiki, file, setting, issues, statistics

urlpatterns = [
    url(r'^index/$', home.index, name='index'),

    url(r'^register/$', account.register, name='register'),
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
    url(r'^login/$', account.login, name='login'),
    url(r'^login/sms/$', account.login_sms, name='login_sms'),
    url(r'^logout/$', account.logout, name='logout'),
    url(r'^image/code/$', account.image_code, name='image_code'),

    url(r'^project/list/$', project.project_list, name='project_list'),
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),

    url(r'^manage/(?P<project_id>\d+)/', include([
        url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
        url(r'^dashboard/issues/chart/$', dashboard.issues_chart, name='issues_chart'),

        url(r'^wiki/$', wiki.wiki, name='wiki'),
        url(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        url(r'^wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        url(r'^wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),
        url(r'^wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),

        url(r'^file/$', file.file, name='file'),
        url(r'^file/delete/$', file.file_delete, name='file_delete'),
        url(r'^cos/credential/$', file.cos_credential, name='cos_credential'),
        url(r'^file/post/$', file.file_post, name='file_post'),
        url(r'^file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

        url(r'^setting/$', setting.setting, name='setting'),
        url(r'^setting/delete/$', setting.delete, name='setting_delete'),

        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/detail/(?P<issues_id>\d+)/$', issues.issues_detail, name='issues_detail'),
        url(r'^issues/record/(?P<issues_id>\d+)/$', issues.issues_record, name='issues_record'),
        url(r'^issues/change/(?P<issues_id>\d+)/$', issues.issues_change, name='issues_change'),

        url(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

        url(r'^statistics/$', statistics.statistics, name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        url(r'^statistics/project/user/$', statistics.statistics_project_user, name='statistics_project_user'),
    ])),
    url(r'^invite/join/(?P<code>\w+)/$', issues.invite_join, name='invite_join'),

    url(r'^price/$', home.price, name='price'),
    url(r'^payment/(?P<policy_id>\d+)/$', home.payment, name='payment'),
    url(r'^pay/$', home.pay, name='pay'),
    url(r'^pay/notify/$', home.pay_notify, name='pay_notify'),
]

web/models.py
from django.core.validators import RegexValidator
from django.db import models


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32, db_index=True)
    email = models.EmailField(verbose_name='邮箱', max_length=64)
    password = models.CharField(verbose_name='密码', max_length=64)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=16,
                                    validators=[RegexValidator(r'^1[3,4,5,6,7,8]\d{9}$')])

    def __str__(self):
        return self.username


class Project(models.Model):
    """项目表"""
    COLOR_CHOICES = [
        (1, "#56b8eb"),
        (2, "#f28033"),
        (3, "#ebc656"),
        (4, "#a2d148"),
        (5, "#20BFA4"),
        (6, "#7461c2"),
        (7, "#20bfa3"),
    ]

    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.PositiveSmallIntegerField(verbose_name='颜色', choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    use_space = models.PositiveIntegerField(verbose_name='项目已使用空间', default=0, help_text='以B为单位')
    is_star = models.BooleanField(verbose_name='星标', default=False)

    join_count = models.PositiveSmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    bucket = models.CharField(verbose_name='cos桶', max_length=128)
    region = models.CharField(verbose_name='cos区域', max_length=32)


class ProjectUser(models.Model):
    """项目参与者"""
    user = models.ForeignKey(verbose_name='参与者', to='UserInfo')
    project = models.ForeignKey(verbose_name='项目', to='Project')
    is_star = models.BooleanField(verbose_name='星标', default=False)

    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)


class PricePolicy(models.Model):
    """价格策略表"""
    category_choices = [
        (1, '免费版'),
        (2, '收费版'),
        (3, '其它'),
    ]
    category = models.PositiveSmallIntegerField(verbose_name='收费类型', default=1, choices=category_choices)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间', help_text='以G为单位')
    per_file_size = models.PositiveIntegerField(verbose_name='单文件大小（M）', help_text='以M为单位')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Transaction(models.Model):
    """交易记录"""
    status_choice = [
        (1, '未支付'),
        (2, '已支付'),
    ]
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choice)

    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)
    user = models.ForeignKey(verbose_name='用户', to='UserInfo')
    price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy')

    count = models.PositiveSmallIntegerField(verbose_name='数量（年）', help_text='0表示永久')

    price = models.PositiveIntegerField(verbose_name='实际支付价格')

    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Wiki(models.Model):
    project = models.ForeignKey(verbose_name='项目', to='Project')
    title = models.CharField(verbose_name='标题', max_length=32)
    content = models.TextField(verbose_name='内容')

    depth = models.IntegerField(verbose_name='深度', default=1)

    # 自关联
    parent = models.ForeignKey(verbose_name='父文章', to='Wiki', null=True, blank=True, related_name='children')

    def __str__(self):
        return self.title


class FileRepository(models.Model):
    """ 文件库 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    name = models.CharField(verbose_name='文件夹名称', max_length=32, help_text="文件/文件夹名")
    file_type_choices = [
        (1, '文件'),
        (2, '文件夹'),
    ]
    file_type = models.PositiveSmallIntegerField(verbose_name='类型', choices=file_type_choices)
    file_size = models.PositiveIntegerField(verbose_name='文件大小', null=True, blank=True, help_text='以B为单位')
    parent = models.ForeignKey(verbose_name='父级目录', to='self', related_name='child', null=True, blank=True)
    key = models.CharField(verbose_name='文件储存在COS中的KEY', max_length=128, null=True, blank=True)
    file_path = models.CharField(
        verbose_name='文件路径', max_length=255, null=True, blank=True
    )  # https://桶.cos.ap-beijing/....
    update_user = models.ForeignKey(verbose_name='最近更新者', to='UserInfo')
    update_datetime = models.DateTimeField(verbose_name='更新时间', auto_now=True)


class Issues(models.Model):
    """问题表"""
    project = models.ForeignKey(verbose_name='项目', to='Project')
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType')

    subject = models.CharField(verbose_name='主题', max_length=64)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = [
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    ]
    priority = models.CharField(verbose_name='优先级', max_length=16, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = [
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    ]
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = [
        (1, '公开模式'),
        (2, '隐私模式'),
    ]
    mode = models.PositiveSmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """
    PROJECT_INIT_LIST = ['任务', '功能', 'bug']

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project')

    def __str__(self):
        return self.title


class IssuesReply(models.Model):
    """问题回复"""

    reply_type_choices = [
        (1, '修改记录'),
        (2, '回复'),
    ]
    reply_type = models.PositiveSmallIntegerField(verbose_name='类型', choices=reply_type_choices)

    issues = models.ForeignKey(verbose_name='问题', to='Issues')
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_reply')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True)


class ProjectInvite(models.Model):
    """项目邀请码"""
    project = models.ForeignKey(verbose_name='项目', to='Project')
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = [
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    ]
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_invite')

web/views/dashboard.py
import collections
import datetime
import time

from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render

from web import models


def dashboard(request, project_id):
    # 问题的数据处理
    status_dict = dict()
    for key, text in models.Issues.status_choices:
        status_dict[key] = {'text': text, 'count': 0}

    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']

    # 项目成员
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id', 'user__username')

    # 最近的10个问题
    top_ten_object = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[:10]

    context = {
        'status_dict': status_dict,
        'user_list': user_list,
        'top_ten_object': top_ten_object,
    }

    return render(request, 'web/dashboard.html', context)


def issues_chart(request, project_id):
    """概览页面生成highchart时所需数据"""

    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]

    # select xxxx,1 as ctime from xxxx
    # select id,name,email from table;
    # select id,name, strftime("%Y-%m-%d",create_datetime) as ctime from table;
    # "DATE_FORMAT(web_transaction.create_datetime,'%%Y-%%m-%%d')"
    result = models.Issues.objects.filter(
        project_id=project_id, create_datetime__gte=today - datetime.timedelta(days=30)
    ).extra(
        select={'ctime': "strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}
    ).values('ctime').annotate(ct=Count('id'))

    for item in result:
        date_dict[item['ctime']][1] = item['ct']

    return JsonResponse({'status': True, 'data': list(date_dict.values())})

web/views/setting.py
from django.shortcuts import render, redirect

from utils.tencent.cos import delete_bucket
from web import models


def setting(request, project_id):
    return render(request, 'web/setting.html')


def delete(request, project_id):
    if request.method == 'GET':
        return render(request, 'web/setting_delete.html')

    project_name = request.POST.get('project_name')

    if request.lxyker.user != request.lxyker.project.creator:
        return render(request, 'web/setting_delete.html', {'error': '权限不足！'})
    if not project_name or project_name != request.lxyker.project.name:
        return render(request, 'web/setting_delete.html', {'error': '项目名称不正确！'})

    # 执行删除项目操作：1、删除cos中的桶；2、删除数据库中的所有文件
    delete_bucket(request.lxyker.project.bucket, request.lxyker.project.region)
    models.Project.objects.filter(id=project_id).delete()

    return redirect('project_list')

web/views/statistics.py
import collections

from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render

from web import models


def statistics(request, project_id):
    """统计页面"""
    return render(request, 'web/statistics.html')


def statistics_priority(request, project_id):
    """按照优先级生成饼图。（返回数据）"""
    # data_list格式如下
    # data_list = [
    #     {
    #         'name': 'apple',
    #         'y': 10,
    #     },
    #     {
    #         'name': 'banana',
    #         'y': 22,
    #     },
    # ]

    # 找到所有的问题，根据优先级分组，每个优先级的问题数量
    start = request.GET.get('start')
    end = request.GET.get('end')

    # 1.构造字典
    data_dict = collections.OrderedDict()
    for key, text in models.Issues.priority_choices:
        data_dict[key] = {'name': text, 'y': 0}

    # 2.去数据查询所有分组得到的数据量
    result = models.Issues.objects.filter(
        project_id=project_id, create_datetime__gte=start, create_datetime__lt=end,
    ).values('priority').annotate(ct=Count('id'))

    # 3.把分组得到的数据更新到data_dict中
    for item in result:
        data_dict[item['priority']]['y'] = item['ct']

    return JsonResponse({'status': True, 'data': list(data_dict.values())})


def statistics_project_user(request, project_id):
    """项目成员每个人被分配的任务数量（问题类型的配比）"""
    start = request.GET.get('start')
    end = request.GET.get('end')

    # 1. 所有项目成员 及 未指派成员
    all_user_dict = collections.OrderedDict()
    all_user_dict[request.lxyker.project.creator.id] = {
        'name': request.lxyker.project.creator.username,
        'status': {item[0]: 0 for item in models.Issues.status_choices}
    }
    all_user_dict[None] = {
        'name': '未指派',
        'status': {item[0]: 0 for item in models.Issues.status_choices}
    }
    user_list = models.ProjectUser.objects.filter(project_id=project_id)
    for item in user_list:
        all_user_dict[item.user_id] = {
            'name': item.user.username,
            'status': {item[0]: 0 for item in models.Issues.status_choices}
        }

    # 2. 去数据库获取相关的所有问题
    issues = models.Issues.objects.filter(project_id=project_id, create_datetime__gte=start, create_datetime__lt=end)
    for item in issues:
        if not item.assign:
            all_user_dict[None]['status'][item.status] += 1
        else:
            all_user_dict[item.assign_id]['status'][item.status] += 1

    # 3.获取所有的成员
    categories = [data['name'] for data in all_user_dict.values()]

    # 4.构造字典
    """
    data_result_dict = {
        1:{name:新建,data:[1，2，3，4]},
        2:{name:处理中,data:[3，4，5]},
        3:{name:已解决,data:[]},
        4:{name:已忽略,data:[]},
        5:{name:待反馈,data:[]},
        6:{name:已关闭,data:[]},
        7:{name:重新打开,data:[]},
    }
    """
    data_result_dict = collections.OrderedDict()
    for item in models.Issues.status_choices:
        data_result_dict[item[0]] = {'name': item[1], "data": []}

    for key, text in models.Issues.status_choices:
        # key=1, text='新建'
        for row in all_user_dict.values():
            count = row['status'][key]
            data_result_dict[key]['data'].append(count)

    context = {
        'status': True,
        'data': {
            'categories': categories,
            'series': list(data_result_dict.values())
        },
    }

    return JsonResponse(context)

web/templates/web/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}
    首页
{% endblock %}

{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static 'image/index/index-1.png' %}" alt="">
    </div>
{% endblock %}

web/templates/web/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}加入项目{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-danger no-radius">
                <h4><i class="fa fa-exclamation-triangle" aria-hidden="true"></i>{{ error }}</h4>
            </div>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i>成功加入项目！</h4>
                <a href="{% url 'dashboard' project_id=project.id %}">点击跳转至项目</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

web/templates/web/login_sms.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %}
    短信登录
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">短信登录</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}

            <div>
                <div style="float: right;"><a href="{% url 'login' %}">密码登录？</a></div>
            </div>

            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="登录"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        });

        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $('.error-msg').empty();
                // 获取用户输入的手机号：输入框由form生成，id默认形式为 id_(字段名)
                var mobilePhone = $('#id_mobile_phone').val();
                // Ajax请求将手机号、tpl值发送后台准备校验
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: 'GET',
                    data: {mobile_phone: mobilePhone, tpl: 'login'},
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            // 向'send_sms'提交了数据，且提交的数据通过了form验证
                            // 开始倒计时
                            sendSmsRemind();
                        } else {
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    },
                })
            })
        }

        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒后重新获取');
                time -= 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)
        }

        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                $.ajax({
                    url: "{% url 'login_sms' %}",
                    type: "POST",
                    data: $('#smsForm').serialize(),
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            // form表单中的数据都校验通过了
                            // 直接让前端跳转到指定的URL去
                            location.href = res.go_url;
                        } else {
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            });
                        }
                    },
                });
            })
        }
    </script>
{% endblock %}

web/templates/web/payment.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %} 订单 {% endblock %}

{% block content %}

    <div class="container">
        <h2>订单信息</h2>
        <table class="table">
            <thead>
            <tr>
                <th>订单</th>
                <th>单价</th>
                <th>数量</th>
                <th>原价</th>
                <th>原订单抵扣</th>
                <th>实际支付</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ policy_object.title }}</td>
                <td>¥{{ policy_object.price }}</td>
                <td>{{ number }}</td>
                <td>¥{{ origin_price }}</td>
                <td>¥{{ balance }}</td>
                <td>¥{{ total_price }}</td>
            </tr>
            </tbody>
        </table>

{#        如果有之前的交易记录#}
        {% if transaction %}
            <div class="alert alert-warning">
                <div>原订单抵扣：¥{{ balance }}</div>
                <div style="margin-top: 10px">
                    原订单的时间为 {{ transaction.start_datetime }}
                    ~ {{ transaction.end_datetime }}，且实际支付¥{{ transaction.price }}
                </div>
            </div>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'pay' %}">立即支付</a>
    </div>

{% endblock %}

web/templates/web/register.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %}
    用户注册
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="注册"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        });

        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $('.error-msg').empty();
                // 获取用户输入的手机号：输入框由form生成，id默认形式为 id_(字段名)
                var mobilePhone = $('#id_mobile_phone').val();
                // Ajax请求将手机号、tpl值发送后台准备校验
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: 'GET',
                    data: {mobile_phone: mobilePhone, tpl: 'register'},
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            // 向'send_sms'提交了数据，且提交的数据通过了form验证
                            // 开始倒计时
                            sendSmsRemind();
                        } else {
                            {#console.log(res);#}
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    },
                })
            })
        }

        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒后重新获取');
                time -= 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)
        }

        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                $.ajax({
                    url: "{% url 'register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(),
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            console.log(res);
                            // form表单中的数据都校验通过了
                            // 直接让前端跳转到指定的URL去
                            location.href = res.go_url;
                        } else {
                            console.log(res);
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            });
                        }
                    },
                });
            })
        }
    </script>
{% endblock %}